### PR TITLE
Update the swift-argument-parser to version 0.2.0. 

### PR DESCRIPTION
**Pull request by cgrindel**
This is a great tool. When I tried to add it to my project, I received a version reconciliation error from the Swift Package Manager.

### CODE REVIEW

**Review by mattpolzin — CHANGES_REQUESTED** [review]
Thanks! Appreciate you getting the code up to date with the latest improvements to argument parser. 

I generally approve of the stylistic changes but the one thing I’d like to revert are the spaces you’ve added around the range operator (0...100).

**Comment by cgrindel** [comment]
Sorry about the formatting changes. They are from `swiftformat`. I thought that I had disabled ALE which runs swiftformat. Apparently, it wasn't. 😉 

I reverted the space in the range. I also backed out an added space to one of the brackets.

**Review by mattpolzin — APPROVED** [review]
Great. Thanks again! I’ve been meaning to find and integrate a linter with rules I like into my projects but just haven’t gotten around to it so my style is a bit ad hoc at the moment.

**Comment by mattpolzin** [comment]
I’ll release a new version this evening.

**Pull request merged**
