### PR TITLE
Add Makefile to ease installation on MacOS 

### PR DESCRIPTION
**Pull request by edelabar**
This also enables easier Homebrew installation. I'm currently using it with a private Homebrew Tap, but I'd love to add it to the Homebrew repository if you're interested.

### CODE REVIEW

**Review by mattpolzin — APPROVED** [review]

**Comment by mattpolzin** [comment]
Thanks. Happy to merge a Makefile. 

> I'd love to add it to the Homebrew repository if you're interested.

if you are offering to add it yourself, I’m certainly ok with you doing so. I don’t know if it is frowned upon for someone not responsible for maintaining a project to add it to a package repository, but assuming it is acceptable, you have my blessing.

**Comment by mattpolzin** [comment]
Does it make any difference to your use-cases for the Makefile if I create a new release/tag or not? I’m inclined not to bother with a new release for the Makefile addition unless it’s helpful.

**Comment by edelabar** [comment]
I don't need it for the Makefile, but it would be helpful and appreciated with my private Brew formula if you don't mind creating the release. 

Would you mind if I submitted to the main Homebrew repository? I don't believe I need anything else from you to do it, but you're the repo owner so I'll honor your wishes.

Thanks for sharing this, it saved me a ton of time figuring out the JSON format myself!

**Comment by mattpolzin** [comment]
> Would you mind if I submitted to the main Homebrew repository?

I think it's a great addition to Homebrew if you or others will find it useful. Absolutely feel free to submit it.

**Comment by edelabar** [comment]
Thanks for the tag! Unfortunately it's being rejected from Homebrew for two reasons:

```
  * 0.11.3 is a GitHub pre-release.
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

I'm trying to drum-up some stars or watches from my coworkers, I'll keep you updated...

**Pull request merged**
